# Supabase Configuration
[supabase]
url = "https://knoszjtkcpjzbnllavhz.supabase.co"
key  = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtub3N6anRrY3BqemJubGxhdmh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMjcxODgsImV4cCI6MjA2ODYwMzE4OH0.t_2DvbHrjz9Zf2rmclmgMmDgcHG_DFw_S6AuNrS8zJU"

# OpenAI Configuration  
[openai]
api_key = "your_openai_api_key"

# Alpha Vantage Configuration
[alpha_vantage]
api_key = "EFAYN4MOOAHOJ2YR"

# Goldman Sachs Configuration (Optional)
[goldman_sachs]
client_id = "your_gs_client_id"
client_secret = "your_gs_client_secret"
